# dataset
data_root: /root/autodl-tmp/
dataset: web-car
n_classes: 196
rescale_size: 448
crop_size: 448

# network & optimization
arch: resnet50
opt: sgd
batch_size: 64
epochs: 120
lr: 0.01
lr_decay: cosine:10
warmup_epochs: 5
warmup_lr: 0.01
warmup_lr_plan: constant
weight_decay: 3.0e-4
use_fp16: true

# hyper-params
eps: 0.1
alpha: 0.3
beta: 0.8
gamma: 0.001
fdim: 512
queue_length: 32000
n_neighbors: 10
topK: 10
topK_decay: 1000
tau_m: 0.98
delta: 0.0
knet_m: 0.99
hdim: 2
transform: strong
cls4ood: nl
cls4id: ce
ncr_lossfunc: kldiv
integrate_mode: or
ood_criterion: div
threshold_generator: per_class_mean
conf_weight: true

# A1
local_evidence: false
local_evidence_every: 5
local_evidence_max_batches: 20
local_evidence_cam_quantile: 0.85
local_evidence_use_teacher: true
local_evidence_min_area: 0.05
local_evidence_max_area: 0.45
local_evidence_bbox_padding: 0.02
local_evidence_cam_type: weightcam
local_evidence_save_images: false
local_evidence_image_max_samples: 8

# C1
part_ce: true
part_ce_weight: 0.5
part_ce_groups: clean
part_ce_use_teacher_cam: true
part_ce_log: true
part_ce_gate: true
part_ce_gate_type: percentile
part_ce_gate_threshold: 0.10
part_ce_gate_keep_ratio: 0.50
part_ce_gate_start_epoch: 20

# C2
id_candidate: false

# D1
multi_part: false

# D2
d2_diag: false

# logging
log_root: ./results/
log_proj: benchmark_webfg
log_name: resnet50-web-car-C1
